### PR TITLE
Logging fixes / improvements

### LINKED ISSUE #553: Verbose logging too verbose in SQLiteWrapper
This is a request to change the current logging for SQLiteWrapper. While testing with trace mode enabled, it becomes very difficult to track the messages I am interested in due to many SQLiteWrapper logs as below:
```
2021-02-26 10:54:22.630817-0800 AEPDemoAppSwiftUI[4979:133160] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
2021-02-26 10:54:22.632890-0800 AEPDemoAppSwiftUI[4979:133159] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
2021-02-26 10:54:22.633574-0800 AEPDemoAppSwiftUI[4979:133159] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
2021-02-26 10:54:22.634191-0800 AEPDemoAppSwiftUI[4979:133159] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
2021-02-26 10:54:22.634789-0800 AEPDemoAppSwiftUI[4979:133159] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
2021-02-26 10:54:22.635393-0800 AEPDemoAppSwiftUI[4979:133159] [AEP SDK TRACE - <SQLiteWrapper>] Successfully opened connection to database at /example/Library/Caches/com.adobe.edge
```

I am proposing to log messages when something wrong happens and the SQLiteWrapper is unable to open the database, instead of logging on success.

### PR DESCRIPTION
**Pull request by cdhoffmann**
Fixes #553 and #698.

For #698, simply changed the rules downloader to return a result to allow consumers to have more control over the logging / error handling. For the app id manifest logs, simply added a trace log for the successful case so that customers can also know when we succeed. 

For #553, simply removed the success case as it is too repetitive.

### CODE REVIEW

File: AEPCore/Sources/configuration/Configuration.swift [hunk 1]
```diff
@@ -59,6 +59,7 @@ class Configuration: NSObject, Extension {
             createSharedState(data: config, event: nil)
             // notify rules engine to load cached rules
             if let rulesURLString = config[ConfigurationConstants.Keys.RULES_URL] as? String {
+                Log.trace(label: name, "Reading rules from cache")
```
Comment (praveek) [inline AEPCore/Sources/configuration/Configuration.swift:62]: Can you modify it to Reading rules from cache for URL \(rulesURLString)?

File: AEPCore/Sources/configuration/LaunchIDManager.swift [hunk 2]
```diff
@@ -39,6 +39,7 @@ struct LaunchIDManager {
     /// - Returns: appId loaded from persistence, nil if not present
     func loadAppIdFromPersistence() -> String? {
         if let appId = dataStore.getString(key: ConfigurationConstants.DataStoreKeys.PERSISTED_APPID) {
+            Log.trace(label: logTag, "Loading App ID from persistence")
```
Comment (praveek) [inline AEPCore/Sources/configuration/LaunchIDManager.swift:42]: Can you also add appId to log message? Even better option would be to move this log message to calling function.

File: AEPCore/Sources/configuration/LaunchIDManager.swift [hunk 3]
```diff
@@ -50,6 +51,7 @@ struct LaunchIDManager {
     func loadAppIdFromManifest() -> String? {
         if let appId = ServiceProvider.shared.systemInfoService.getProperty(for: ConfigurationConstants.CONFIG_MANIFEST_APPID_KEY) {
             saveAppIdToPersistence(appId: appId)
+            Log.trace(label: logTag, "Loading App ID from manifest")
```
Comment (praveek) [inline AEPCore/Sources/configuration/LaunchIDManager.swift:54]: Same as above

File: AEPCore/Sources/rules/LaunchRulesEngine+Downloader.swift [hunk 4]
```diff
@@ -24,13 +24,22 @@ public extension LaunchRulesEngine {
...
         let rulesDownloader = RulesDownloader(fileUnzipper: FileUnzipper())
-        rulesDownloader.loadRulesFromUrl(rulesUrl: url) { data in
-            guard let data = data, let rules = JSONRulesParser.parse(data)  else {
-                Log.debug(label: RulesConstants.LOG_MODULE_PREFIX, "Failed to load rules from url: \(urlString)")
-                return
+        rulesDownloader.loadRulesFromUrl(rulesUrl: url) { result in
+            switch result {
+            case .success(let data):
+                guard let rules = JSONRulesParser.parse(data) else {
+                    Log.debug(label: RulesConstants.LOG_MODULE_PREFIX, "Unable to parse rules from data")
```
Comment (praveek) [inline AEPCore/Sources/rules/LaunchRulesEngine+Downloader.swift:31]: "Unable to parse rules for data from url: \(urlString)"

File: AEPCore/Sources/rules/RulesDownloader.swift [hunk 5]
```diff
@@ -23,16 +23,11 @@ struct RulesDownloader: RulesLoader {
...
-        case unableToCreateTempDirectory
-        case unableToStoreDataInTempDirectory
-    }
-
     func loadRulesFromCache(rulesUrl: URL) -> Data? {
         return getCachedRules(rulesUrl: rulesUrl.absoluteString)?.cacheable
     }
 
-    func loadRulesFromUrl(rulesUrl: URL, completion: @escaping (Data?) -> Void) {
+    func loadRulesFromUrl(rulesUrl: URL, completion: @escaping (Result<Data, RulesDownloaderError>) -> Void) {
```
Comment (praveek) [inline AEPCore/Sources/rules/RulesDownloader.swift:30]: +1

File: AEPCore/Sources/configuration/LaunchIDManager.swift (hunk 2 above)
Comment (cdhoffmann) [reply AEPCore/Sources/configuration/LaunchIDManager.swift:42]: I agree that a better option would be to remove logs from these functions and move to calling function but what do you think about the following: We call `loadAppIdFromPersistence` and `loadAppIdFromManifest` from the `loadAppId` function. 

```
    func loadAppId() -> String? {
        // Prefer appId stored in persistence over in manifest
        return loadAppIdFromPersistence() ?? loadAppIdFromManifest()
    }
```

So we either change how clean this function is in order to provide logs here. Or we provide logs in the callers of `loadAppId()` but then we wont get specific logs knowing if the app id was loaded from manifest or persistence. Just that it was loaded.

Comment (praveek) [reply AEPCore/Sources/configuration/LaunchIDManager.swift:42]: I am fine with the current logs. Can we change the current logs to also print App Id as it will be useful for debugging.            
`Log.trace(label: logTag, "Loaded App ID \(appId) from persistence")`

**Review by praveek — APPROVED** [review]
